#! /bin/sh

killall polybar

sxhkd &
nitrogen --restore &
polybar wolfenbar &
mpd --no-config &
picom -b

#### BSPWM monitors ####
bspc monitor -d 1 2 3 4 5 6 7 8 9

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  3
bspc config window_gap                    5
bspc config top_padding                   5
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	              "#1e1e1e"
bspc config focused_border_color	      "#9f40ff"
bspc config presel_feedback_color	      "#9f40ff"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a eDP)

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Caja state=floating

bspc rule -a "Code - OSS" desktop='^1'
bspc rule -a jetbrains-toolbox desktop='^1' state=floating
bspc rule -a jetbrains-pycharm desktop='^1'

bspc rule -a Alacritty desktop='^2'
bspc rule -a Chromium desktop='^2'

bspc rule -a Brave-browser desktop='^3'
bspc rule -a Firefox desktop='^3'

bspc rule -a discord desktop='^4'

bspc rule -a KeePassXC desktop='^5' state=floating
bspc rule -a PCSX2 desktop='^5' state=floating

bspc rule -a Blueman-manager desktop='^6' state=floating
bspc rule -a Virt-manager desktop='^6' state=floating

bspc rule -a Gimp desktop='^8' state=floating follow=on

### Fix for Java applications... ###
wmname LG3D
